Vagrant.configure("2") do |config|
  config.vm.box = "debian/trixie64"

  # config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "qemu"
    libvirt.memory = 1024
    libvirt.cpus = 1
  end

  config.vm.define "msouiyehS" do |mS|
    mS.vm.hostname = "msouiyehS"
    mS.vm.network "private_network", ip: "192.168.56.110"
    #mS.vm.provision "shell", inline: "ufw disable"
    mS.vm.provision "shell", inline: "apt-get update && apt-get install -y curl"
    mS.vm.provision "shell", inline: <<-SHELL
    curl -sfL https://get.k3s.io | K3S_TOKEN=IOT sh -s - server --node-ip 192.168.56.110 --write-kubeconfig-mode 644
    SHELL
  end

  config.vm.define "msouiyehSW" do |mSW|
    mSW.vm.hostname = "msouiyehSW"
    mSW.vm.network "private_network", ip: "192.168.56.111"
    #mSW.vm.provision "shell", inline: 'ufw disable'
    mSW.vm.provision "shell", inline: "apt-get update && apt-get install -y curl"
    mSW.vm.provision "shell", inline: <<-SHELL
    curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=IOT sh -s - agent  --node-ip 192.168.56.111
    SHELL
  end
end
