Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.box_version = "1.0.282"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.cpus = 1
  end

  config.vm.define "msouiyehS" do |mS|
    mS.vm.hostname = "msouiyehS"
    mS.vm.network "private_network", ip: "192.168.56.110"
  end

  config.vm.define "msouiyehSW" do |mSW|
    mSW.vm.hostname = "msouiyehSW"
    mSW.vm.network "private_network", ip: "192.168.56.111"
  end
end
